global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "codespaces"
    scheme: https  # Tambahkan ini
    static_configs:
      - targets: ["${CODESPACE_NAME}-8000.githubpreview.dev"]
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification untuk development